### ISSUE TITLE
Unable to see changes on GH app

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/content-semantics#1]
@thomasjbradley 
I'm working on the Beets assignment. I dragged the file to atom and saved a new file as index.html.
I then wrote some code and went to commit the changes I made on the GitHub app but it's blank. 

Also in Atom, I don't see the html file I saved in the first place on the left hand panel.

**Comment by thomasjbradley** [comment]
That sounds like the HTML file is in the wrong folder.
You could try doing an Save-As on the HTML file and re-saving it into the beets assignment folder.

**Comment by sheri-thomson** [comment]
Found it! You were right :) Thanks..
